spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: MONGO-SERVER
  data:
    mongodb:
      uri: mongodb://10.1.0.89:30002/test_jhl
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
